version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql-security/data
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
volumes:
  db_data:



